version: "3.9"

services:
  postgres:
    container_name: db
    image: postgres:16.1-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todo-app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - go-build:/go/pkg/mod

volumes:
  go-build:
  postgres_data: