version: "3.9"

services:
  todo-app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - go-build:/go/pkg/mod

volumes:
  go-build: